export const FETCH_USERS = 'FETCH_USERS'
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USERS_LIST_ERROR = 'USERS_LIST_ERROR'
export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST'

export const FETCH_TWEETS = 'FETCH_TWEETS'
export const TWEETS_LIST_SUCCESS = 'TWEETS_LIST_SUCCESS'
export const TWEETS_LIST_ERROR = 'TWEETS_LIST_ERROR'
